spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9010/pgvector-test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: openai/gpt-oss-120b:free
          temperature: 0.0
      http-client:
        read-timeout: 600000ms
        connect-timeout: 60000ms
        connection-request-timeout: 600000ms
jwt:
  secret-key: ${JWT_SECRET_KEY}

stripe:
  api:
    secret: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

client.url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123
    project-bucket: projects