spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret-key: aashgdshbjhdkmhgdkwqulqbdcsdnkjfhql

stripe:
  api:
    secret: sk_test_51TfJD4CIg4ftiynMlqTGWAgQK0XoLu9bvQS2x1jazXUcMNbFMZ7qFYa83GlekgSQsjNhxV8PHQHe1RIvwSyVgoal00Jahjeik9
  webhook:
    secret: whsec_eddd5a482a12631116c637423e9680c8e1ea6f7bd8be3f7a6bf201c55a7b8d07
client.url: http://localhost:8080