spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/pournima238/lovable-config-server
      username: pournima238
      password: ${GITHUB_PAT}
      default-label: main

server.port: 8888
